from . import response_status
from . import admin_airport
from . import airport_enquiry
from . import airport_service
from . import res_partner
from . import res_company
from . import res_config_settings
from . import sale_order
from . import product
from . import account_move
from . import bank
from . import service_category
from . import airport_service_type
from . import travel_class
from . import enquiry_status
from . import uaa_mail_body
from . import additional_charge
from . import payment
from . import mail
from . import status_history
